"use client";

import { useEffect, useState } from "react";
import { Sparkles, TrendingUp, AlertTriangle, AlertCircle, Lightbulb } from "lucide-react";

interface Insight {
  type: "positive" | "warning" | "critical" | "opportunity";
  title: string;
  insight: string;
}

const typeConfig = {
  positive:    { icon: TrendingUp,   color: "text-emerald-400", bg: "bg-emerald-500/10", border: "border-emerald-500/20" },
  warning:     { icon: AlertTriangle, color: "text-amber-400",   bg: "bg-amber-500/10",   border: "border-amber-500/20" },
  critical:    { icon: AlertCircle,   color: "text-red-400",     bg: "bg-red-500/10",     border: "border-red-500/20" },
  opportunity: { icon: Lightbulb,     color: "text-violet-400",  bg: "bg-violet-500/10",  border: "border-violet-500/20" },
};

export default function AIInsightsPanel() {
  const [insights, setInsights] = useState<Insight[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);

  const fetchInsights = async () => {
    setLoading(true);
    setError(false);
    try {
      const res = await fetch("/api/insights");
      const data = await res.json();
      setInsights(data.insights);
    } catch {
      setError(true);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { fetchInsights(); }, []);

  return (
    <div className="bg-white/[0.03] rounded-xl border border-white/[0.06] p-5">
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-2">
          <Sparkles className="w-4 h-4 text-violet-400" />
          <h3 className="text-sm font-semibold text-gray-300">AI Insights</h3>
          <span className="text-xs text-gray-600">· generated by Claude</span>
        </div>
        <button
          onClick={fetchInsights}
          className="text-xs text-violet-400 hover:text-violet-300 font-medium transition-colors"
        >
          Refresh
        </button>
      </div>

      {loading && (
        <div className="space-y-3">
          {[...Array(4)].map((_, i) => (
            <div key={i} className="h-16 bg-white/[0.04] rounded-lg animate-pulse" />
          ))}
        </div>
      )}

      {error && (
        <p className="text-sm text-red-400">Failed to load insights.</p>
      )}

      {!loading && !error && (
        <div className="space-y-3">
          {insights.map((item, i) => {
            const cfg = typeConfig[item.type];
            const Icon = cfg.icon;
            return (
              <div key={i} className={`flex gap-3 p-3 rounded-lg border ${cfg.bg} ${cfg.border}`}>
                <Icon className={`w-4 h-4 mt-0.5 shrink-0 ${cfg.color}`} />
                <div>
                  <p className={`text-xs font-semibold ${cfg.color}`}>{item.title}</p>
                  <p className="text-xs text-gray-400 mt-0.5">{item.insight}</p>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
